### ISSUE TITLE
Windows path problem

### ISSUE THREAD

**Issue by legnaleurc** [legnaleurc/monitor#2]
Maybe cygwin may solve it.

**Comment by devnoname120** [comment]
I do not understand why this commit is necessary: https://github.com/legnaleurc/monitor/commit/c9af775f3cb55f79c416085627f241ac243d46fe

Does [`chdir()`](https://github.com/legnaleurc/monitor/blob/c9af775f3cb55f79c416085627f241ac243d46fe/monitord/__main__.py#L12) not work on Unix systems?

This function [officially supported them until Python 3.4](https://docs.python.org/3.4/library/os.html#os.chdir), but the string 'Availability: Unix, Windows.' mysteriously [disappeared on Python 3.5](https://docs.python.org/3.5/library/os.html#os.chdir) and later versions.

**Comment by legnaleurc** [comment]
> This function officially supported them until Python 3.4, but the string 'Availability: Unix, Windows.' mysteriously disappeared on Python 3.5 and later versions.

I think they omit it is because that means it works on almost all platforms.

The main problem is `chromedriver` needs to be able to be found in `PATH`.
It looks like it will search current working directory in Windows, but not in Unix-like OSs.
So in Unix-like OSs, passing absolute path is necessary.
Changing the current working directory is not wise if you have multiple tasks that will run at the same time.

I hope these external files stay outside from the source directory (maybe `tempfile.gettempdir()`).
There should be an `Environment` class to deal with these things.

**Comment by legnaleurc** [comment]
I think this will not be a problem anymore after switching to docker/vagrant approach.
